spring.datasource.url=jdbc:postgresql://localhost:5480/NeoSupply
spring.datasource.username=postgres
spring.datasource.password=123123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.properties.hibernate.format_sql=true
server.port=8082
jwt.secret-key=4ad3b54cd8f0ae87d59166fbac10e6611afc3f0028f81eccf5362360eb5c7dd6
logging.file.name=/var/log/myapp/myapp.log
logging.level.root=INFO