spring.datasource.url=jdbc:postgresql://localhost:5480/NeoSupply
spring.datasource.username=postgres
spring.datasource.password=123123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.properties.hibernate.format_sql=true
